[package]
name = "web"
version = "0.1.0"
authors = ["smehlhoff"]
edition = "2018"

[dependencies.db]
path = "../db"

[dependencies]
actix-files = "0.1.1"
actix-rt = "0.2.2"
actix-web = "1.0.0"
env_logger = "0.6.1"
serde = "1.0.92"
serde_derive = "1.0.92"
serde_json = "1.0.39"
